FROM python:3.13-bookworm
COPY ./requirements.txt /aries-test-harness/
WORKDIR /aries-test-harness
RUN pip install -r requirements.txt

RUN \
    echo "==> Install stuff not in the requirements..."   && \
    pip install --no-cache-dir \
        aiohttp

COPY . /aries-test-harness

ENTRYPOINT ["behave"]
